### ISSUE TITLE
Shouldn't this part of the code be changed?

### ISSUE THREAD

**Issue by Neltherion** [HoangPham3003/SVM-Active-Learning-for-Relevance-Feedback#1]
Hi

Thanks for the implementation of the paper.

I was wondering if the code here should be changed:

https://github.com/HoangPham3003/SVM-Active-Learning-for-Relevance-Feedback/blob/60aa3aa951631c622e279a1d229c8ddb0dadd07e/rf.py#L181

From this:

![image](https://github.com/HoangPham3003/SVM-Active-Learning-for-Relevance-Feedback/assets/22426131/437407d4-cc2e-4e99-89da-26e5affcd53d)

To This:

![image](https://github.com/HoangPham3003/SVM-Active-Learning-for-Relevance-Feedback/assets/22426131/a7852e35-c4e8-4ef7-b025-254cb7d40ae7)

**Comment by HoangHPham** [comment]
Thanks for your findings. That line is actually an error. It can be edited as you mentioned above or simply deleted. I will update again in the near future.

**Comment by Neltherion** [comment]
Thanks for the quick reply.

But if the line is deleted, then we won't have `DSE_arr` anywhere in the code, since the only place `compute_DSE` is used, is here:

![image](https://github.com/HoangPham3003/SVM-Active-Learning-for-Relevance-Feedback/assets/22426131/dc5a9422-0f4c-4140-a91d-ca5da3c37563)

**Comment by HoangHPham** [comment]
It might be a bit of a misunderstanding, I mean it's possible to delete or edit the line of code: `DSE_arr = np.array(DS_arr)`.

**Comment by Neltherion** [comment]
I get it now, Thanks!
